/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen flex flex-col`}
      >
        <header className="border-b border-border sticky top-0 z-50 bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="mx-auto w-full max-w-6xl px-6 py-4 flex items-center justify-between">
            <a href="/" className="flex items-center gap-2 group">
              <span className="inline-block h-6 w-6 rounded-full bg-accent transition-transform duration-300 group-hover:rotate-6" />
              <span className="font-semibold tracking-tight">Eurin Hash</span>
            </a>
            <nav className="flex items-center gap-6 text-sm">
              <a href="/about" className="hover:underline">À propos</a>
              <a href="/projects" className="hover:underline">Projets</a>
              <a href="/skills" className="hover:underline">Compétences</a>
              <a href="/vision" className="hover:underline">Vision</a>
              <a href="/contact" className="hover:underline">Contact</a>
            </nav>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t border-border">
          <div className="mx-auto w-full max-w-6xl px-6 py-8 text-center text-sm text-muted-foreground">
            ©2025 Eurin Hash
          </div>
        </footer>
      </body>
    </html>
  );
}
